# Page settings

baseURL = "https://swathik90.github.io/my-cv/"
languageCode = "en"
title = "Swathi's CV"
theme = "hugo-devresume-theme"
googleAnalytics = "G-NGGP93EN1J"






[params]
    author = "Swathi Kandiyil"
    description = "Multi Talented Engineer who loves Software Testing & Content Writing in addition to baking"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Swathi Kandiyil"
        tagline = "Copywriter | Software Tester"
        avatar = "avatar.jpg"







    [params.contact]
        enable = true
        location = "Rostock, Germany"

        [[params.contact.list]]
        icon = "fab fa-linkedin"
        url = "https://www.linkedin.com/in/swathi-kandiyil-482985166/"
        text = "Swathi Kandiyil"
        [[params.contact.list]]
        icon = "fas fa-at"
        url = "mailto:0rgxq92fb@mozmail.com"
        text = "protected@mozmail.com"
        [[params.contact.list]]
        icon = "fab fa-github"
        url = "https://github.com/swathik90"
        text = "github/swathik90"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Content Writer"
        [[params.skills.list.items]]
        details = "SEO Practices"
        [[params.skills.list.items]]
        details = "Web Content Writer"
        [[params.skills.list.items]]
        details = "Copywriter"
        [[params.skills.list.items]]
        details = "Technical Documentation"
        [[params.skills.list.items]]
        details = "Content Research"
        [[params.skills.list.items]]
        details = "Content Editor"

        [[params.skills.list]]
        title = "Software Tester"
        [[params.skills.list.items]]
        details = "Manual Testing"
        [[params.skills.list.items]]
        details = "User Testing"
        [[params.skills.list.items]]
        details = "Quality Assurance"
        [[params.skills.list.items]]
        details = "Web Application Testing"

        [[params.skills.list]]
        title = "Programming"
        [[params.skills.list.items]]
        details = "Python"
        [[params.skills.list.items]]
        details = "C++"
        [[params.skills.list.items]]
        details = "MATLAB"
        [[params.skills.list.items]]
        details = "C"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Graduate work: Master of Communication Engineering with PhD"
        university = "Indian Institute of Technology, Madras"
        dates = "2013 - 2019"
        [[params.education.list]]
        degree = "BTech Electronics and communication engineering"
        university = "Amrita School of Engineering, Coimbatore"
        dates = "2007 - 2011"








    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "Native"
        [[params.languages.list]]
        name = "Hindi"
        level = "Professional"
        [[params.languages.list]]
        name = "Malayalam"
        level = "Native"
        [[params.languages.list]]
        name = "German"
        level = "Beginner"






    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Baking"
        [[params.interests.list]]
        name = "Trekking"
        [[params.interests.list]]
        name = "Travelling"








    [params.summary]
        enable = true
        text = "Summarise your career here. Donec quam felis, ultricies nec, pellentesque eu. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.  Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Senior Software Engineer"
        dates = "2019 - Present"
        company = "Google"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."
        [[params.experience.list.items]]
        details = "Etiam ultricies nisi vel augue."

        [[params.experience.list]]
        title = "Lead Software Developer"
        dates = "2016 - 2019"
        company = "Apple"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."

        [[params.experience.list]]
        title = "Senior Software Developer"
        dates = "2014 - 2016"
        company = "Dropbox"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Senior Developer"
        dates = "2013 - 2014"
        company = "Uber"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

        [[params.experience.list]]
        title = "Backend Developer"
        dates = "2014 - 2016"
        company = "Amazon"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Frontend Developer"
        dates = "2013 - 2014"
        company = "Startup"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."











    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."










    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"








    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/swathik90"
        title = "swathik90"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/swathi-kandiyil-482985166"
        title = "Swathi Kandiyil"





