# Page settings

baseURL = "https://swathik90.github.io/my-cv/"
languageCode = "en"
title = "Swathi's CV"
theme = "hugo-devresume-theme"
googleAnalytics = "G-NGGP93EN1J"






[params]
    author = "Swathi Kandiyil"
    description = "Multi Talented Engineer who loves Software Testing & Content Writing in addition to baking"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Swathi Kandiyil"
        tagline = "Copywriter | Software Tester"
        avatar = "avatar.jpg"







    [params.contact]
        enable = true
        location = "Rostock, Germany"

        [[params.contact.list]]
        icon = "fab fa-linkedin"
        url = "https://www.linkedin.com/in/swathi-kandiyil-482985166/"
        text = "Swathi Kandiyil"
        [[params.contact.list]]
        icon = "fas fa-at"
        url = "mailto:0rgxq92fb@mozmail.com"
        text = "protected@mozmail.com"
        [[params.contact.list]]
        icon = "fab fa-github"
        url = "https://github.com/swathik90"
        text = "github/swathik90"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Content Writer"
        [[params.skills.list.items]]
        details = "SEO Practices"
        [[params.skills.list.items]]
        details = "Web Content Writer"
        [[params.skills.list.items]]
        details = "Copywriter"
        [[params.skills.list.items]]
        details = "Technical Documentation"
        [[params.skills.list.items]]
        details = "Content Research"
        [[params.skills.list.items]]
        details = "Content Editor"

        [[params.skills.list]]
        title = "Software Tester"
        [[params.skills.list.items]]
        details = "Manual Testing"
        [[params.skills.list.items]]
        details = "User Testing"
        [[params.skills.list.items]]
        details = "Quality Assurance"
        [[params.skills.list.items]]
        details = "Web Application Testing"

        [[params.skills.list]]
        title = "Programming"
        [[params.skills.list.items]]
        details = "Python"
        [[params.skills.list.items]]
        details = "C++"
        [[params.skills.list.items]]
        details = "MATLAB"
        [[params.skills.list.items]]
        details = "C"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Graduate work: Master of Communication Engineering with PhD"
        university = "Indian Institute of Technology, Madras"
        grade = "CGPA: 8.5"
        dates = "2013 - 2019"
        [[params.education.list]]
        degree = "BTech Electronics and communication engineering"
        university = "Amrita School of Engineering, Coimbatore"
        grade = "CGPA: 8.7"
        dates = "2007 - 2011"
        [[params.education.list]]
        degree = "12th Grade"
        university = "Kendriya Vidyalaya, Coimbatore"
        grade = "Total: 94%"
        dates = "2006 - 2007"







    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "Native"
        [[params.languages.list]]
        name = "Hindi"
        level = "Professional"
        [[params.languages.list]]
        name = "Malayalam"
        level = "Native"
        [[params.languages.list]]
        name = "German"
        level = "Beginner"






    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Baking"
        [[params.interests.list]]
        name = "Trekking"
        [[params.interests.list]]
        name = "Travelling"








    [params.summary]
        enable = true
        text = "With a strong foot in Electrical and Communication Engineering, I started my career as Software Test Engineer for embedded systems. I later pursued further research in the Communication Engineering sector. Concurrently, I found my interest incline towards Copywriting and Quality Assurance tasks."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Copy Writer / Content Writer"
        dates = "2018 - 2021"
        company = "Wittypen"
        details = "Delivered well-researched and grammatically correct content pieces in various formats for multiple verticals Incorporated SEO techniques and parameters for better content visibility ranking."
        [[params.experience.list.items]]
        details = "SEO Optimised content"
        [[params.experience.list.items]]
        details = "Technical Research and Product Analysis"
        [[params.experience.list.items]]
        details = "Engaging content development"

        [[params.experience.list]]
        title = "Quality Assurance / Software Tester"
        dates = "2015 - 2020"
        company = "DezignEx"
        details = "As a Manual QA tester for Web and Mobile applications, I had good working experience in writing Test Cases and Test Suites. The QA was an integral part of DevOps in an Agile framework. During this time I had the opportunity to work with several test tools and automation tools. I am driven and passionate about technology and have a key eye for the details which makes me good at Quality and Assurance."
        [[params.experience.list.items]]
        details = "Manual Testing"
        [[params.experience.list.items]]
        details = "Agile / DevOps Framework"
        [[params.experience.list.items]]
        details = "Web Application Testing"

        [[params.experience.list]]
        title = "Graduate Teaching Assistant"
        dates = "2013 - 2019"
        company = "Indian Institute of Technology, Madras"
        details = "Assisted professors in correcting exam papers, clearing student doubts, evaluating assignments and creating study material."

        [[params.experience.list]]
        title = "Software Test Engineer"
        dates = "2011 - 2012"
        company = "Robert Bosch Engineering & Business Solutions Private Limited"
        details = "I was part of the agile test team involved in testing the embedded systems for ABS & ECS of automobiles. The project was for clients like Mercedes and BMW. Main experience with manual testing. We used to perform black box testing as well."
        [[params.experience.list.items]]
        details = "Blackbox Testing"
        [[params.experience.list.items]]
        details = "Embeded Systems testing"










    [params.projects]
        enable = false

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."










    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"








    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/swathik90"
        title = "swathik90"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/swathi-kandiyil-482985166"
        title = "Swathi Kandiyil"


    [params.footer]
    copyright = "CaptV"





