# Page settings

baseURL = "https://swathik90.github.io/my-cv/"
languageCode = "en"
title = "Swathi's CV"
theme = "hugo-devresume-theme"
googleAnalytics = "G-NGGP93EN1J"

[params]
    author = "Swathi Kandiyil"
    description = "Master's graduate in Electrical Engineering with expertise in communication systems, signal processing, and machine learning"

    primaryColor = "#0891b2"
    textPrimaryColor = "#000000"

    [params.profile]
        enable = true
        name = "Swathi Kandiyil"
        tagline = "Electrical Engineering | Communication Systems | Signal Processing"
        avatar = "avatar.jpg"

    [params.contact]
        enable = true
        location = "Lübeck, Germany"

        [[params.contact.list]]
        icon = "fab fa-linkedin"
        url = "https://www.linkedin.com/in/swathi-kandiyil-482985166/"
        text = "Swathi Kandiyil"
        [[params.contact.list]]
        icon = "fas fa-at"
        url = "mailto:0rgxq92fb@mozmail.com"
        text = "0rgxq92fb@mozmail.com"
        [[params.contact.list]]
        icon = "fab fa-github"
        url = "https://github.com/swathik90"
        text = "github/swathik90"

    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Programming"
        [[params.skills.list.items]]
        details = "Python"
        [[params.skills.list.items]]
        details = "PyTorch"
        [[params.skills.list.items]]
        details = "NumPy"
        [[params.skills.list.items]]
        details = "C++"
        [[params.skills.list.items]]
        details = "C"
        [[params.skills.list.items]]
        details = "MATLAB"
        [[params.skills.list.items]]
        details = "Julia"
        [[params.skills.list.items]]
        details = "Git/GitHub"
        [[params.skills.list.items]]
        details = "OpenMP"

        [[params.skills.list]]
        title = "Communication Engineering"
        [[params.skills.list.items]]
        details = "Signal Processing"
        [[params.skills.list.items]]
        details = "Error Control Coding"
        [[params.skills.list.items]]
        details = "MIMO OFDM Simulation"
        [[params.skills.list.items]]
        details = "Wireless Communication Systems"

        [[params.skills.list]]
        title = "Mathematics"
        [[params.skills.list.items]]
        details = "Probability & Statistics"
        [[params.skills.list.items]]
        details = "Numerical Methods"
        [[params.skills.list.items]]
        details = "Calculus"
        [[params.skills.list.items]]
        details = "Linear Algebra"

        [[params.skills.list]]
        title = "Software Testing"
        [[params.skills.list.items]]
        details = "Manual Testing"
        [[params.skills.list.items]]
        details = "User Testing"
        [[params.skills.list.items]]
        details = "Web Application Testing"
        [[params.skills.list.items]]
        details = "Black Box Testing"

        [[params.skills.list]]
        title = "Content Creation"
        [[params.skills.list.items]]
        details = "Content Research"
        [[params.skills.list.items]]
        details = "Web Content Writing"
        [[params.skills.list.items]]
        details = "SEO Optimization"
        [[params.skills.list.items]]
        details = "Technical Documentation"

    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Master of Science in Electrical Engineering - Informatik"
        university = "Universität Rostock"
        grade = "Grade: 1.9"
        dates = "2023 - 2025"
        [[params.education.list.items]]
        details = "Master's Thesis: Investigation of Quantised Spatial Modulation Systems"
        [[params.education.list.items]]
        details = "Developed simulation models using Python, PyTorch, and NumPy"
        [[params.education.list.items]]
        details = "Coursework: Digital Signal Processing, Error Control Coding, Artificial Neural Networks, Explainable AI, High Performance Computing"

        [[params.education.list]]
        degree = "Master's & PhD* in Communication Engineering"
        university = "Indian Institute of Technology, Madras"
        grade = "CGPA: 8.5/10"
        dates = "2013 - 2019"
        [[params.education.list.items]]
        details = "Completed graduate coursework and qualified for PhD-level research"
        [[params.education.list.items]]
        details = "PhD research (incomplete): Mean Field Theory Analysis of Dynamic Bandwidth Allocation in WiFi Communication"

        [[params.education.list]]
        degree = "BTech in Electronics and Communication Engineering"
        university = "Amrita School of Engineering, Coimbatore"
        grade = "CGPA: 8.34/10"
        dates = "2007 - 2011"
        [[params.education.list.items]]
        details = "Internship at Airport Authority of India"
        [[params.education.list.items]]
        details = "Bachelor's Thesis: Fault Diagnosis using Zero-Decision Diagrams"

        [[params.education.list]]
        degree = "12th Grade"
        university = "Kendriya Vidyalaya, Coimbatore"
        grade = "Total: 94%"
        dates = "2006 - 2007"

    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "Linear Regression for Business Statistics"
        body = "Coursera"
        date = "2020"
        [[params.awards.list]]
        name = "Introduction to Data Analysis Using Excel"
        body = "Coursera"
        date = "2020"
        [[params.awards.list]]
        name = "Business Applications of Hypothesis Testing"
        body = "Coursera"
        date = "2020"

    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "Native"
        [[params.languages.list]]
        name = "Hindi"
        level = "Native"
        [[params.languages.list]]
        name = "Malayalam"
        level = "Native"
        [[params.languages.list]]
        name = "Tamil"
        level = "Conversational"
        [[params.languages.list]]
        name = "German"
        level = "Intermediate"

    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Baking"
        [[params.interests.list]]
        name = "Travelling"
        [[params.interests.list]]
        name = "Gardening"
        [[params.interests.list]]
        name = "Reading"

    [params.summary]
        enable = true
        text = "Master's graduate in Electrical Engineering – Information Technology from Universität Rostock, with hands-on experience in communication systems, signal processing, and applied machine learning. Completed thesis on quantised spatial modulation systems using Python, PyTorch, and NumPy. Proficient in developing and validating algorithms for wireless communication applications, seeking roles to apply advanced technical expertise in industry or R&D."

    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Student Job - Research"
        dates = "2024 - 2025"
        company = "Universität Rostock"
        details = "Analyzed Approximate Message Passing (AMP) algorithms for decoding in spatial modulation systems. Investigated performance variations and convergence issues through simulation and result evaluation using Python (PyTorch)."

        [[params.experience.list]]
        title = "Software Engineer (Part Time)"
        dates = "2015 - 2020"
        company = "DezignEx"
        details = "Performed manual testing for web and mobile applications, designing and executing test cases within an Agile DevOps environment. Ensured high-quality software delivery through meticulous validation."
        [[params.experience.list.items]]
        details = "Manual Testing"
        [[params.experience.list.items]]
        details = "Agile / DevOps Framework"
        [[params.experience.list.items]]
        details = "Web Application Testing"

        [[params.experience.list]]
        title = "Part-time Content & Tutoring"
        dates = "2017 - 2021"
        company = "Wittypen, Chegg, Course Hero"
        details = "Created SEO-optimized content and provided tutoring support. Delivered clear explanations and step-by-step solutions to support student learning across multiple platforms."

        [[params.experience.list]]
        title = "Teaching Assistant"
        dates = "2013 - 2019"
        company = "Indian Institute of Technology, Madras"
        details = "Supported professors by evaluating exam papers, addressing student queries, evaluating assignments, and creating study materials."

        [[params.experience.list]]
        title = "Associate Software Engineer"
        dates = "2011 - 2012"
        company = "Robert Bosch Engineering & Business Solutions"
        details = "Validated embedded systems for ABS and ECS in automobiles. Performed manual black box testing for clients including Mercedes and BMW."
        [[params.experience.list.items]]
        details = "Embedded Systems Testing"
        [[params.experience.list.items]]
        details = "Black Box Testing"
        [[params.experience.list.items]]
        details = "Agile Team Collaboration"

    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Investigation of Quantised Spatial Modulation Systems"
        meta = "Master's Thesis"
        tagline = "Compared quantised spatial modulation using AMP decoding with conventional MIMO-OFDM. Designed and implemented simulations in Python to evaluate performance based on error rate curves."

        [[params.projects.list]]
        title = "Comparison of Spatial Modulation and MIMO Techniques"
        meta = "Pre-Thesis Project"
        tagline = "Compared spatial modulation with AMP-based decoding against conventional MIMO systems without OFDM. Designed and implemented simulations in Python to evaluate system performance."

    [params.information]
        enable = false

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/swathik90"
        title = "swathik90"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/swathi-kandiyil-482985166"
        title = "Swathi Kandiyil"

    [params.footer]
        copyright = "CaptV"